// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/example/v1/messages.proto

package example

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateNote - запрос CreateNote
type CreateNoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// note - заметка
	Note          *CreateNoteRequest_Note `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_api_example_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_example_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteRequest) GetNote() *CreateNoteRequest_Note {
	if x != nil {
		return x.Note
	}
	return nil
}

// CreateNoteResponse - ответ CreateNote
type CreateNoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// note_id - id созданной записи
	NoteId        string `protobuf:"bytes,1,opt,name=note_id,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_api_example_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_example_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNoteResponse) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

// Note - note message
type CreateNoteRequest_Note struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// title - название заметки
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// content - содержание заметки
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// author_id - id автора
	AuthorId      uint64 `protobuf:"varint,3,opt,name=author_id,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest_Note) Reset() {
	*x = CreateNoteRequest_Note{}
	mi := &file_api_example_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest_Note) ProtoMessage() {}

func (x *CreateNoteRequest_Note) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest_Note.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest_Note) Descriptor() ([]byte, []int) {
	return file_api_example_v1_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateNoteRequest_Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest_Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNoteRequest_Note) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

var File_api_example_v1_messages_proto protoreflect.FileDescriptor

const file_api_example_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/example/v1/messages.proto\x12\x0eapi.example.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xdc\x05\n" +
	"\x11CreateNoteRequest\x12E\n" +
	"\x04note\x18\x01 \x01(\v2&.api.example.v1.CreateNoteRequest.NoteB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x04note\x1a\xf8\x03\n" +
	"\x04Note\x12\x88\x01\n" +
	"\x05title\x18\x01 \x01(\tBr\x92Ab*\x05title2\x1fназвание заметкиJ\x12\"My Awesome Title\"x\x80\x02\x80\x01\x03\x8a\x01\x10^[a-zA-Z0-9 -]+$\x9a\x02\x01\a\xa2\x02\x06string\xe0A\x02\xbaH\ar\x05\x10\x03\x18\x80\x02R\x05title\x12{\n" +
	"\acontent\x18\x02 \x01(\tBa\x92AQ*\x05title2\x1fназвание заметкиJ\x14\"My Awesome Content\"x\x80 \x80\x01\x01\x9a\x02\x01\a\xa2\x02\x06string\xe0A\x02\xbaH\ar\x05\x10\x01\x18\x80 R\acontent\x12c\n" +
	"\tauthor_id\x18\x03 \x01(\x04BE\x92A8*\tauthor_id2\x0fid автораJ\x041234i\x00\x00\x00\x00\x00\x00\xf0?\x9a\x02\x01\x05\xa2\x02\x06string\xe0A\x02\xbaH\x042\x02 \x00R\tauthor_id:\x82\x01\x92A\x7f\n" +
	"2*\x04Note2\fnote message\xd2\x01\x05title\xd2\x01\acontent\xd2\x01\tauthor_id*I\n" +
	"\x1cFind out more about validate\x12)https://github.com/bufbuild/protovalidate:\x84\x01\x92A\x80\x01\n" +
	"3*\x11CreateNoteRequest2\x17запрос CreateNote\xd2\x01\x04note*I\n" +
	"\x1cFind out more about validate\x12)https://github.com/bufbuild/protovalidate\"\xe6\x02\n" +
	"\x12CreateNoteResponse\x12\xc3\x01\n" +
	"\anote_id\x18\x01 \x01(\tB\xa8\x01\x92A\xa4\x01*\anote_id2\"id созданной записиJ&\"2438ac3c-37eb-4902-adef-ed16b4431030\"\x8a\x01E^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$\xa2\x02\x04uuidR\anote_id:\x89\x01\x92A\x85\x01\n" +
	"+*\x12CreateNoteResponse2\x15ответ CreateNote*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gatewayB\xbf\x01\n" +
	"\x12com.api.example.v1B\rMessagesProtoP\x01Z@github.com/moguchev/balun_meetup_2025/pkg/api/example/v1;example\xa2\x02\x03AEX\xaa\x02\x0eApi.Example.V1\xca\x02\x0eApi\\Example\\V1\xe2\x02\x1aApi\\Example\\V1\\GPBMetadata\xea\x02\x10Api::Example::V1b\x06proto3"

var (
	file_api_example_v1_messages_proto_rawDescOnce sync.Once
	file_api_example_v1_messages_proto_rawDescData []byte
)

func file_api_example_v1_messages_proto_rawDescGZIP() []byte {
	file_api_example_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_example_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_example_v1_messages_proto_rawDesc), len(file_api_example_v1_messages_proto_rawDesc)))
	})
	return file_api_example_v1_messages_proto_rawDescData
}

var file_api_example_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_example_v1_messages_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),      // 0: api.example.v1.CreateNoteRequest
	(*CreateNoteResponse)(nil),     // 1: api.example.v1.CreateNoteResponse
	(*CreateNoteRequest_Note)(nil), // 2: api.example.v1.CreateNoteRequest.Note
}
var file_api_example_v1_messages_proto_depIdxs = []int32{
	2, // 0: api.example.v1.CreateNoteRequest.note:type_name -> api.example.v1.CreateNoteRequest.Note
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_example_v1_messages_proto_init() }
func file_api_example_v1_messages_proto_init() {
	if File_api_example_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_v1_messages_proto_rawDesc), len(file_api_example_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_example_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_example_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_example_v1_messages_proto_msgTypes,
	}.Build()
	File_api_example_v1_messages_proto = out.File
	file_api_example_v1_messages_proto_goTypes = nil
	file_api_example_v1_messages_proto_depIdxs = nil
}
