// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/example/v1/service.proto

package example

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_example_v1_service_proto protoreflect.FileDescriptor

const file_api_example_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1capi/example/v1/service.proto\x12\x0eapi.example.v1\x1a\x1dapi/example/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xab\x03\n" +
	"\x0eExampleService\x12\x80\x02\n" +
	"\n" +
	"CreateNote\x12!.api.example.v1.CreateNoteRequest\x1a\".api.example.v1.CreateNoteResponse\"\xaa\x01\x92A\x8b\x01\x12\n" +
	"CreateNote\x1a7CreateNote - метод создания заметки\"D\n" +
	"\x12Find out more Echo\x12.https://github.com/grpc-ecosystem/grpc-gateway\x82\xd3\xe4\x93\x02\x15:\x04note\"\r/api/v1/notes\x1a\x95\x01\x92A\x91\x01\n" +
	"\x0eExampleService\x12,ExampleService - серивис пример\x1aQ\n" +
	"\x1fFind out more about EchoService\x12.https://github.com/grpc-ecosystem/grpc-gatewayB\xfa\x03\x92A\xb8\x02\x12\xc2\x01\n" +
	"\x0fExample Service\"N\n" +
	"\x1bЛеонид Ченский\x12\x15https://t.me/leoscode\x1a\x18leolegrand1014@gmail.com*X\n" +
	"\x14BSD 3-Clause License\x12@https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE2\x050.1.0*\x02\x01\x022\x10application/json:\x10application/jsonrI\n" +
	"\x17More about gRPC-Gateway\x12.https://github.com/grpc-ecosystem/grpc-gateway\n" +
	"\x12com.api.example.v1B\fServiceProtoP\x01Z@github.com/moguchev/balun_meetup_2025/pkg/api/example/v1;example\xa2\x02\x03AEX\xaa\x02\x0eApi.Example.V1\xca\x02\x0eApi\\Example\\V1\xe2\x02\x1aApi\\Example\\V1\\GPBMetadata\xea\x02\x10Api::Example::V1b\x06proto3"

var file_api_example_v1_service_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),  // 0: api.example.v1.CreateNoteRequest
	(*CreateNoteResponse)(nil), // 1: api.example.v1.CreateNoteResponse
}
var file_api_example_v1_service_proto_depIdxs = []int32{
	0, // 0: api.example.v1.ExampleService.CreateNote:input_type -> api.example.v1.CreateNoteRequest
	1, // 1: api.example.v1.ExampleService.CreateNote:output_type -> api.example.v1.CreateNoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_example_v1_service_proto_init() }
func file_api_example_v1_service_proto_init() {
	if File_api_example_v1_service_proto != nil {
		return
	}
	file_api_example_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_v1_service_proto_rawDesc), len(file_api_example_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_example_v1_service_proto_goTypes,
		DependencyIndexes: file_api_example_v1_service_proto_depIdxs,
	}.Build()
	File_api_example_v1_service_proto = out.File
	file_api_example_v1_service_proto_goTypes = nil
	file_api_example_v1_service_proto_depIdxs = nil
}
